language: scala
dist: xenial

# This build connects to saucelabs which limits the number of concurrent connections to 5.
# As a consequence, the max concurrent jobs setting un travis' web UI must be set to 5
# https://docs.travis-ci.com/user/web-ui/#limit-concurrent-jobs

scala:
  - 2.12.10
  - 2.13.1

services:
  - xvfb

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - CHROME_BIN=/usr/bin/google-chrome
    - DISPLAY=:99.0
  matrix:
    - TRAVIS_JDK=8
    - TRAVIS_JDK=11

# The build matrix produced with the settings above causes a rather big number of travis jobs.
# The sauce_connect addon below has a limit of 5 concurrent connections so this repository uses a Travis-CI.com
# setting that limits the number of concurrent jobs per repo.
#  See https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

before_script:
  - "mkdir -p ~/tmp/bin"
  - "pushd ~/tmp/bin && wget -c https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && popd"
  - "pushd ~/tmp/bin && wget -c https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz && tar -xzvf geckodriver-v0.24.0-linux64.tar.gz && popd"
  - "chmod -vv +x ~/tmp/bin/*"
  - "export PATH=$HOME/tmp/bin:$PATH"

script: scripts/run-ci

addons:
  firefox: "latest"
  chrome: stable
  apt:
    packages:
    - unzip
    - dbus-x11
  sauce_connect:
    username: will_sargent
    access_key: d809febf-5037-4857-aefb-ac652b4c5315

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.jabba/jdk
    - $HOME/.sbt
    - $HOME/.coursier

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  slack:
    secure: irCWE97/NCRRJinXNh+cJ9BUG3PtMOynN9/2VP80KUK1oxvrr8GtJmMT8b/tMg9JFVifWrrU/gepdVwetXbWUZjik0HnFFlGusQvwqVBeRgHZKqAy1GHQAuKz59SXOuJ/rHOPVZ28GmT8VmUB/LpHw527dmuJJ79OCcE8NEVE8w=
  webhooks:
    urls: https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
